### ISSUE TITLE
Missing vulkan_intel.h

### ISSUE THREAD

**Issue by bkaradzic** [krh/vkcube#1]
Where I can find `vulkan_intel.h`?

**Comment by krh** [comment]
It's in our mesa vulkan branch, or if you're using the Fedora RPMs, you can
get it from the anvil-devel RPM.

Kristian

On Tue, Feb 16, 2016 at 8:13 PM, Branimir Karadžić <notifications@github.com

**Comment by bkaradzic** [comment]
Ok, got it. Does it only work with Wayland? Is there way to use it on X11?

Some build instructions, and general Linux setup how to get this up and running would be helpful.

I'm running it on Linux Mint with Vulkan PPA from:
https://launchpad.net/~canonical-x/+archive/ubuntu/vulkan

**Comment by krh** [comment]
I works under X11, Wayland and KMS. You'll need XCB headers and an X server
has DRI3 to run it under X.

Kristian

On Wed, Feb 17, 2016 at 9:40 AM, Branimir Karadžić <notifications@github.com

**Comment by krh** [comment]
vulkan_intel.h now optional.
