### ISSUE TITLE
Cube rotation flickering

### ISSUE THREAD

**Issue by pisto** [krh/vkcube#17]
I am not sure this is a problem with vkcube, however with the xcb backend, mesa 13.0.3 and intel Ivy Bridge I get this kind of flickering https://www.pisto.horse/cube.mkv 
Note that I don't get this with the kms backend.

**Comment by OlliC** [comment]
Can confirm on Fedora 25 with mesa 13.0.4 on Intel Skylake HD 520. Wayland backends works but it opens a window with no decorations. xcb window has decorations but cube flickers.

**Comment by gfxstrand** [comment]
Does this still happen with latest mesa?  13.0 is EOL and no longer receiving updates at this point.

**Comment by krh** [comment]
This may have been the lack of write domain annotation in the anv relocs, causing the blit in the xserver to not synchronize.
