### ISSUE TITLE
Window resize

### ISSUE THREAD

**Issue by ghost** [krh/vkcube#22]
Hello,
I would like to report that resizing of the application's window freezes whole system. I could not get any debugging info as the system crashes before the application. I am running `Debian GNU/Linux testing (buster) x86_64` with the Linux kernel `4.11.6-1`. The application was running under `gnome-shell` in version `3.22.3-3` on top of Xorg server in version `1.19.3-2`. The version of `libvulkan1` is `1.0.54.0+dfsg1-1` and `libgbm1` is `17.2.0~git20170807+17.2.29df4dee-0ubuntu0ricotz`. The Xorg server is running under NVIDIA driver in version `375.82-1` on top of the `NVIDIA GeForce GTX 1070`.
I hope this is all the information you will need. And thank you in advance for looking into this issue.

**Comment by SE2Dev** [comment]
I also have this issue:
+ OS: `Debian GNU/Linux (stretch) 9.1`
+ Kernel: `4.9.0-3-amd64`
+ GPU: `NVIDIA GeForce 770M`
+ Graphics Driver: `nvidia-driver` (from the official Debian repo)

Sometimes my system un-freezes for a single frame and over the course of 5 - 10 minutes I can force close vkcube and restore my system to a usable state, but not always. I've checked the system logs to see if anything shows up during this behavior, but I didn't find anything out of the ordinary.

**Comment by ghost** [comment]
Ok, today I got around to investigate what is causing the issue. And after few google searches and comparing issues with vkcube's code I have stumbled upon problems with swap chain on NVIDIA cards. (https://github.com/RPCS3/rpcs3/issues/1770) In vkcube's code I then found this line:
https://github.com/krh/vkcube/blob/0e8ec923c4b6ccf3a83912ef93cd4005becc6734/main.c#L857
If you comment it out everything works fine. I am not sure whether there are any side effects.
Then I tried adding `vc->swap_chain = VK_NULL_HANDLE;` instead of the commented out line. And it also works fine. Although I think it is not even close to correct.
I also do not think this is a fix but rather a hack, please let me know whether this helps.

**Comment by krh** [comment]
I think perhaps rendering and swap chain creation is racing with on-going window resizing on the X server side in lines 885 to 902. We should check the vk calls there and in create_swapchain for errors and just skip to line 903 to schedule a new repaint and try again.

**Comment by ghost** [comment]
Tried few things and my "fix" aka hack makes a huge memory leak.
Here is log from valgrind
`valgrind --leak-check=full --show-leak-kinds=all --log-file=memory.*.log ./vkcube`
- memory.nosizing.log http://sprunge.us/Nhcf
- memory.sizing.log http://sprunge.us/fNKY

I have also tried some stuff in the repaint block(883 to 904) like skipping but with no luck. But I am not very experienced with C and Vulkan API.
