### ISSUE TITLE
Why link with libvulkan-1?

### ISSUE THREAD

**Issue by Jajcus** [krh/vkcube#3]
The official Linux Vulkan loader soname is 'libvulkan.so.1"  and the library name for linking is 'vulkan' (libvulkan.so), not 'vulkan-1' (libvulkan-1.so). 

I can see the commit changing '-lvulkan' to '-lvulkan-1'. Why was this change made?

**Comment by MattSturgeon** [comment]
Seems fixed in 687e2d240e4effa2a61878b864ea7fd41a8a2473
