### ISSUE TITLE
Nvidia optimus

### ISSUE THREAD

**Issue by AnAkkk** [krh/vkcube#8]
I have just installed the Nvidia Vulkan driver on my Nvidia optimus laptop, and found out that vkcube only see my intel GPU, not the Nvidia one.

This is the output when I run vkcube:

> Xlib:  extension "NV-GLX" missing on display ":1".
> Xlib:  extension "NV-GLX" missing on display ":1".
> WARNING: Haswell Vulkan support is incomplete
> 1 physical devices
> anv_device.c:414: FINISHME: Get correct values for VkPhysicalDeviceLimits
> vendor id 8086, device name Intel(R) Haswell Mobile

This may not be an issue related to vkcube, although it's the only thing I can test with.

**Comment by AnAkkk** [comment]
It still doesn't work with the latest Nvidia 364.16 but I have noticed this in nvidia ICD file:

> "layer": {
>         "name": "VK_LAYER_NV_optimus",
>         "type": "INSTANCE",
>         "library_path": "libGLX_nvidia.so.0",
>         "api_version" : "1.0.8",
>         "implementation_version" : "1",
>         "description" : "NVIDIA Optimus layer",
>         "functions": {
>             "vkGetInstanceProcAddr": "vk_optimusGetInstanceProcAddr"
>         },
>         "disable_environment": {
>             "DISABLE_LAYER_NV_OPTIMUS": ""
>         }
>     }

Is that something to support optimus inside vulkan?

**Comment by rhymoid** [comment]
The only way I can get Vulkan working with a discrete NVIDIA is using `DISPLAY=:8 optirun vulkaninfo` (or any other Vulkan application instead of `vulkaninfo`).

* If I just use `vulkaninfo`, I get `Xlib:  extension "NV-GLX" missing on display ":0.0".` once.
* If I just use `optirun vulkaninfo`, it should work, but I get the same warning/error.
* If I use `DISPLAY=:8 optirun vulkaninfo`, it works.

This seems to be [a known issue](Bumblebee-Project/Bumblebee#769) with bumblebee.

**Comment by krh** [comment]
Ideally, Vulkan should report more than one device on the system and the application should then pick which one it wants. From the above, Vulkan only reports 1 device and vkcube always picks the first one anyway. Perhaps you tried this at a time where vkcube linked directly to the Intel driver and as such would only find Intel devices.

Now, vkcube links to the generic loader, which should be able to locate all devices on the system. We could add a command line option to pick which device to use - I'd be happy to merge that if you figure it out.

**Comment by kaimast** [comment]
For me, vkcube only seems to see the NVIDIA one now, not the Intel GPU. I am on Arch Linux with the NVIDIA 530 drivers.

See the output below. Lshw shows to devices, with ids 0 and 2. Only id 0 seems to work. I tried 1 and some other ids as well without success...

```
~> lshw -C display
WARNING: you should run this program as super-user.
  *-display
       description: 3D controller
       product: TU117M [GeForce GTX 1650 Ti Mobile]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:201 memory:b3000000-b3ffffff memory:70000000-7fffffff memory:80000000-81ffffff ioport:3000(size=128)
  *-display
       description: VGA compatible controller
       product: CometLake-H GT2 [UHD Graphics]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 05
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: iomemory:600-5ff iomemory:400-3ff irq:168 memory:604a000000-604affffff memory:4000000000-400fffffff ioport:4000(size=64) memory:c0000-dffff
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
~> vkcube --gpu_number 2  
GPU 2 specified is not present, GPU count = 1
Specified GPU number is not present
~> vkcube-wayland --gpu_number 2  
GPU 2 specified is not present, GPU count = 1
Specified GPU number is not present
```
